@host = http://localhost:1234
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk5MTE2ODQ3LCJleHAiOjE2OTk3MjE2NDd9.sGHfWrDb_K6BC6J6XLnvshNIjlRCjRhqbxJnfSycl1o
###
GET {{host}}/clients/
Authorization: Bearer {{token}}
###

POST {{host}}/clients/
Authorization: Bearer {{token}}
Content-Type:application/json

{
    "nombre": "Cliente4"
}
###
POST {{host}}/login
Content-Type:application/json

{
}

###
POST {{host}}/admin/login
Content-Type:application/json

{
    "username": "admin",
    "password" : "admin"
}