@host = http://localhost:1234
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZUlkIjoxLCJpYXQiOjE2OTkxNTY2NzMsImV4cCI6MTY5OTc2MTQ3M30.oXywlXMp5NtFRfaWF8wWV0wP8ooCMMGqNpzCrnz01jM
###
GET {{host}}/clients/
Authorization: Bearer {{token}}
###

POST {{host}}/clients/
Authorization: Bearer {{token}}
Content-Type:application/json


{
    "name": "Cliente2",
    "nationality": "aa",
    "password" : "1234",
    "username" : "c2",
    "idClientType": 1
}
###
POST {{host}}/login
Content-Type:application/json

{
    "username": "admin",
    "password" : "admin"
}

###
POST {{host}}/admin/login
Content-Type:application/json

{
    "username": "admin",
    "password" : "admin"
}